version: "3.9"
services:
  mongo:
    container_name: mongo
    build: 
      dockerfile: Dockerfile.db
    env_file:
      - ./.env

  python-app:
    container_name: myflaskapp
    depends_on:
      - mongo
    build: 
      dockerfile: Dockerfile.app
    restart: always
    env_file:
      - ./.env
    ports:
      - 8080:8080