apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    appProtocol: http
  selector:
    app: mongo