apiVersion: v1
kind: Service
metadata:
  name: flask-restaurant
  namespace: default
  labels:
    app: flask-restaurant
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    appProtocol: http
  selector:
    app: flask-restaurant